#三个配置文件: 一个控制，一个开发环境，一个生产环境

Spring:
  profiles:
    active: dev
  thymeleaf:
    mode: HTML
    cache: false
    check-template: true
    check-template-location: true

book:
  name: 互联网世界观
  isbn: ${random.uuid}
  author: 李善友
  description: ${book.name} ,这本书还不错

